# Generated by Django 3.1.3 on 2020-12-03 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationcategory',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='publication_publicationcategory_adm', to=settings.AUTH_USER_MODEL, verbose_name='Category Admins'),
        ),
        migrations.AddField(
            model_name='publicationcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='publication.publicationcategory', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='publication.publicationcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='publication',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_reg', to='address.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='publication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
