# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160517112445 on 2016-05-17 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0002_auto_20160517_0917'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Is primary')),
                ('amount', models.DecimalField(db_index=True, decimal_places=5, default=0, max_digits=22, verbose_name='Amount')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('date_billed', models.DateField(default=django.utils.timezone.now, verbose_name='Billed date')),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Billed'), (2, 'Paid'), (3, 'Cancelled')], default=0, verbose_name='Bill status')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255, verbose_name='Invoice number')),
                ('description_small', models.CharField(blank=True, default='', max_length=255, verbose_name='Small description')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_bill_cntype', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'Bills',
                'verbose_name': 'Bill',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=3, verbose_name='Currency code')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Name(English')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'verbose_name': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='On date')),
                ('nominal', models.SmallIntegerField(db_index=True, default=1, verbose_name='Nominal')),
                ('official_rate', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=10, verbose_name='Official Rate')),
                ('rate', models.DecimalField(db_index=True, decimal_places=4, default=0, max_digits=10, verbose_name='Rate')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.Currency', verbose_name='Currency')),
            ],
            options={
                'ordering': ('-date', 'currency__code'),
                'verbose_name_plural': 'Exchange Rates',
                'verbose_name': 'Exchange Rate',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('primary', models.BooleanField(default=False, verbose_name='Is primary')),
                ('amount', models.DecimalField(db_index=True, decimal_places=5, default=0, max_digits=22, verbose_name='Amount')),
                ('actor_oid', models.CharField(blank=True, max_length=255, verbose_name='ID of object')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Accepted'), (2, 'Completed'), (3, 'Cancelled')], default=0, verbose_name='Transaction status')),
                ('actor_ctype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_object', to='contenttypes.ContentType', verbose_name='Object Content Type')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_transaction_cntype', to='contenttypes.ContentType')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.Currency', verbose_name='Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'verbose_name': 'Transaction',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='money.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set([('user', 'actor_ctype', 'actor_oid', 'date', 'amount', 'currency')]),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([('currency', 'date', 'rate')]),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together=set([('code',)]),
        ),
    ]
